### ISSUE TITLE
Integración continua con Travis y pruebas con SonarQube

### ISSUE THREAD

**Issue by Dionakra** [Tarkinder/tinder-stalker#2]
En este proyecto es importante que el código esté probado (de ello depende nuestro aprobado), por lo que el código debe pasar las pruebas constantemente en todos sus cambios.

Además, estaría bien probar SonarQube para que nos analice el código.

**Comment by agubelu** [comment]
![6f0](https://cloud.githubusercontent.com/assets/1207202/25861126/1458e772-34e4-11e7-9154-fb45b9cccd23.jpg)

**Comment by Dionakra** [comment]
Yo creo que podemos ir cerrando esto...
